
# creating test files
usethis::use_test("CFSformat")

testthat::test_file("tests/testthat/test-CFSformat.R")


usethis::use_test("quality_assessment")

tests/testthat/helper-data.R

usethis::use_test("models")

usethis::use_test("graphing")

usethis::use_test("misc")

usethis::use_test("mapping")


# generate dt.samples and dt.clim in extdata
library(data.table)
samples69.o <- fread("inst/extdata/samples69.o.csv")
names(samples69)
samples69[, .N, by = .(site_id, latitude, longitude)]

samples69 <- samples69.o[ site_id %in% c("X003b", "X004b", "X005c", "X010d", "X011c", "X012b", " X016c", "X071d"), ]
clim69.o <- fread("inst/extdata/clim69.o.csv")
clim69 <- clim69.o[ site_id %in% c("X003b", "X004b", "X005c", "X010d", "X011c", "X012b", " X016c", "X071d")]

# ring measurement
samples69.o <- fread(system.file("extdata", "samples69.csv", package = "CFSTRenD"))
# samples69 <- Filter(function(x) !all(is.na(x)), samples69)
names(samples69.o)
j <- 39
for (j in ncol(samples69.o):39) {
  if (all(is.na(samples69.o[[j]]))) set(samples69.o, j = j, value = NULL)
}
write.csv(clim69, file = "inst/extdata/clim69.csv", row.names = FALSE, na = "" )
write.csv(samples69.o, file = "inst/extdata/samples69.csv", row.names = FALSE, na = "" )



samples69.o <- fread(system.file("extdata", "samples69.csv", package = "growthTrendR"))
names(samples69.o)
samples69.o[, .N, by = .(site_id, latitude, longitude)]
samples69.1 <- samples69.o[site_id %in% c("X003b", "X011c", "X005c")]
samples69.1 <- samples69.o[!(is.na(`2020`) | is.na(`2019`)  | is.na(`2018`))]
samples69.1[, .N, by = .(site_id)]

library(dplyr)
# Keep only 3 samples per site_id
df_sampled <- samples69.1 %>%
  group_by(site_id) %>%
  slice_sample(n = 3) %>%  # randomly pick 3 rows per group
  ungroup()


names(df_sampled)
cols_to_remove <- as.character(1948:1990)
df_filtered <- df_sampled[, !colnames(df_sampled) %in% cols_to_remove]
setDT(df_filtered)
df_filtered <- df_filtered[site_id %in% c("X003b", "X011c", "X005c")]
write.csv(
  df_filtered,
  file = "inst/extdata/dt.samples.csv",
  row.names = FALSE,
  na = ""
)

clim69 <- fread(system.file("extdata", "clim69.csv", package = "growthTrendR"))
clim69 <- clim69[site_id %in% c("X003b", "X011c", "X005c")]
clim69 <- clim69[year > 1990]

write.csv(clim69, file = system.file("extdata", "clim69.csv", package = "growthTrendR"), row.names = FALSE, na = "")

write.csv(
  clim69,
  file = "inst/extdata/dt.clim.csv",
  row.names = FALSE,
  na = ""
)

# run examples
devtools::run_examples()
devtools::test()


install.packages("pkgdown")  # if not already installed
library(pkgdown)

pkgdown::build_site()



library(growthTrendR)
browseVignettes("growthTrendR")

devtools::build_vignettes()


system("git remote -v")

pkgdown::clean_site()
pkgdown::clean_site(force = TRUE)
pkgdown::build_site()


devtools::check()


usethis::use_git()


# Remove HTML/PDF files from doc
unlink("doc/*.html")
unlink("doc/*.pdf")

# Remove autogenerated R scripts from vignettes
unlink("vignettes/*.R")
unlink("vignettes/*.html")


unlink("doc/*")           # remove rendered vignette files
unlink("vignettes/*.R")   # remove autogenerated R scripts
unlink("vignettes/*.html")# remove local HTML outputs

unlink("inst/rmd/*.R")   # remove autogenerated R scripts
unlink("inst/rmd/*.html")# remove local HTML outputs

devtools::check("growthTrendR", cran = TRUE)

devtools::document()



# Install rhub from CRAN:

  pak::pkg_install("rhub")

  # Setup
  # Switch to the directory of your package, and call rhub::rhub_setup() to add the R-hub workflow file to your package.
  rhub::rhub_setup()

  rhub::rhub_doctor()

  # Run checks
  # Use rhub::rhub_platforms() to get a list of supported platforms and checks:

  rhub::rhub_platforms()
  rhub::rhub_check()



  library(installr)
  updateR()
  install.packages("data.table", repos = "https://rdatatable.gitlab.io/data/")

  install.packages(c('ggplot2', 'patchwork', 'terra', 'raster', 'furrr', 'future', 'pryr'))
  install.packages(c('ggforce', 'ggeffects', 'geosphere', 'MuMIn', 'gstat', 'sf', 'spdep', 'magick'))
